name: CI

# Copy into the workflows subdirectory to use this script.
# see: https://github.com/marketplace/actions/debugging-with-tmate

on: [push]

jobs:

  build:
    env:
      ENV_NAME: hklpy-test-${{ matrix.python-version }}
      PACKAGE: hklpy

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [3.7, 3.8, 3.9]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: set environment name in YAML file
      shell: bash -l {0}
      run: |
        sed -i.bak "s/name: ${PACKAGE}/name: ${ENV_NAME}/g" environment.yml
    - name: tmate session
      uses: mxschmitt/action-tmate@v3
