canonical_axes:
- omega
- chi
- phi
- tth
class: SimulatedE4CV
constraints:
    chi:
        fit: true
        high_limit: 180.0
        low_limit: -180.0
        value: 0.0
    omega:
        fit: true
        high_limit: 180.0
        low_limit: -180.0
        value: 0.0
    phi:
        fit: true
        high_limit: 180.0
        low_limit: -180.0
        value: 0.0
    tth:
        fit: true
        high_limit: 180.0
        low_limit: -180.0
        value: 0.0
datetime: '2023-10-26 16:58:20.819891'
energy_keV: 8.050921974025975
engine: hkl
geometry: E4CV
hklpy_version: 1.0.4+28.gd9a56a4.dirty
library: gi.repository.Hkl
library_version: v5.0.0.3001
mode: bissector
name: e4c
real_axes:
- omega
- chi
- phi
- tth
reciprocal_axes:
- h
- k
- l
samples:
    main:
        U:
        -   - 1.0
            - 0.0
            - 0.0
        -   - 0.0
            - 1.0
            - 0.0
        -   - 0.0
            - 0.0
            - 1.0
        UB:
        -   - 4.079990459207523
            - -2.4982736282101165e-16
            - -2.4982736282101165e-16
        -   - 0.0
            - 4.079990459207523
            - -2.4982736282101165e-16
        -   - 0.0
            - 0.0
            - 4.079990459207523
        lattice:
            a: 1.54
            alpha: 90.0
            b: 1.54
            beta: 90.0
            c: 1.54
            gamma: 90.0
        name: main
        reflections: []
    vibranium:
        U:
        -   - 1.2217304763701863e-05
            - -0.9999999999253688
            - -1.8235863128158895e-15
        -   - -1.4926257043558267e-10
            - -9.139696455822134e-27
            - -1.0000000000000002
        -   - 0.9999999999253688
            - 1.2217304763701863e-05
            - -1.4926257042444305e-10
        UB:
        -   - 1.2217304763701863e-05
            - -0.9999999999253688
            - -1.7623547209572502e-15
        -   - -1.4926257043558267e-10
            - -1.4349296274686127e-42
            - -1.0000000000000002
        -   - 0.9999999999253688
            - 1.221730476364063e-05
            - -1.492626316575311e-10
        lattice:
            a: 6.283185307179586
            alpha: 90.0
            b: 6.283185307179586
            beta: 90.0
            c: 6.283185307179586
            gamma: 90.0
        name: vibranium
        reflections:
        -   flag: 1
            orientation_reflection: false
            position:
                chi: 0.0
                omega: -145.451
                phi: 0.0
                tth: 69.0966
            reflection:
                h: 4.0
                k: 0.0
                l: 0.0
            wavelength: 1.54
        -   flag: 1
            orientation_reflection: true
            position:
                chi: 0.0
                omega: -145.451
                phi: 90.0
                tth: 69.0966
            reflection:
                h: 0.0
                k: 4.0
                l: 0.0
            wavelength: 1.54
        -   flag: 1
            orientation_reflection: true
            position:
                chi: 90.0
                omega: -145.451
                phi: 0.0
                tth: 69.0966
            reflection:
                h: 0.0
                k: 0.0
                l: 4.0
            wavelength: 1.54
wavelength_angstrom: 1.54
