name: e4c
geometry: E4CV
datetime: '2023-10-26 17:36:48.532883'
python_class: SimulatedE4CV
engine: hkl
mode: bissector
hklpy_version: 1.0.5.dev53+g1a1f94d.d20231026
library: gi.repository.Hkl
library_version: v5.0.0.3001
energy_keV: 8.050921974025975
wavelength_angstrom: 1.54
constraints:
    omega:
        low_limit: -180.0
        high_limit: 180.0
        value: 0.0
        fit: true
    chi:
        low_limit: -180.0
        high_limit: 180.0
        value: 0.0
        fit: true
    phi:
        low_limit: -180.0
        high_limit: 180.0
        value: 0.0
        fit: true
    tth:
        low_limit: -180.0
        high_limit: 180.0
        value: 0.0
        fit: true
samples:
    main:
        name: main
        lattice:
            a: 1.54
            b: 1.54
            c: 1.54
            alpha: 90.0
            beta: 90.0
            gamma: 90.0
        reflections: []
        U:
        -   - 1.0
            - 0.0
            - 0.0
        -   - 0.0
            - 1.0
            - 0.0
        -   - 0.0
            - 0.0
            - 1.0
        UB:
        -   - 4.079990459207523
            - -2.4982736282101165e-16
            - -2.4982736282101165e-16
        -   - 0.0
            - 4.079990459207523
            - -2.4982736282101165e-16
        -   - 0.0
            - 0.0
            - 4.079990459207523
    vibranium:
        name: vibranium
        lattice:
            a: 6.283185307179586
            b: 6.283185307179586
            c: 6.283185307179586
            alpha: 90.0
            beta: 90.0
            gamma: 90.0
        reflections:
        -   reflection:
                h: 4.0
                k: 0.0
                l: 0.0
            flag: 1
            wavelength: 1.54
            position:
                omega: -145.451
                chi: 0.0
                phi: 0.0
                tth: 69.0966
            orientation_reflection: false
        -   reflection:
                h: 0.0
                k: 4.0
                l: 0.0
            flag: 1
            wavelength: 1.54
            position:
                omega: -145.451
                chi: 0.0
                phi: 90.0
                tth: 69.0966
            orientation_reflection: true
        -   reflection:
                h: 0.0
                k: 0.0
                l: 4.0
            flag: 1
            wavelength: 1.54
            position:
                omega: -145.451
                chi: 90.0
                phi: 0.0
                tth: 69.0966
            orientation_reflection: true
        U:
        -   - 1.2217304763701863e-05
            - -0.9999999999253688
            - -1.8235863128158895e-15
        -   - -1.4926257043558267e-10
            - -9.139696455822134e-27
            - -1.0000000000000002
        -   - 0.9999999999253688
            - 1.2217304763701863e-05
            - -1.4926257042444305e-10
        UB:
        -   - 1.2217304763701863e-05
            - -0.9999999999253688
            - -1.7623547209572502e-15
        -   - -1.4926257043558267e-10
            - -1.4349296274686127e-42
            - -1.0000000000000002
        -   - 0.9999999999253688
            - 1.221730476364063e-05
            - -1.492626316575311e-10
canonical_axes:
- omega
- chi
- phi
- tth
real_axes:
- omega
- chi
- phi
- tth
reciprocal_axes:
- h
- k
- l
